Changes for 10.12
GnuPG 2.1.21

diff --git a/create_gpg b/create_gpg
--- a/create_gpg
+++ b/create_gpg
@@ -12,6 +12,7 @@ function printUsage {
 
 ABI=64     ## default is 64-bit build
 LIBS_FILE=libs.txt
+set -o pipefail
 
 
 if [ "$1" = "-h" -o "$1" = "--help" ]; then
@@ -41,6 +42,11 @@ if [ "${BASEDIR:0:1}" != "/" ]; then
   # ensure that BASEDIR is an absolute path
   BASEDIR=$(pwd)"/$BASEDIR"
 fi
+exec &> >(tee -a "$MAIN_DIR/create_gpg.log")
+
+
+echo -n "Build started at "; date
+
 
 step=0
 
@@ -76,8 +82,12 @@ function unpack {
 
   case $fn in
   .lz)
-    (lunzip -k -c $inFile | tar xf -) || doFail $inFile
-    ;;
+	  lunzip=lunzip
+	  if ! command -v lunzip &>/dev/null; then
+		  lunzip="lzip -d"
+	  fi
+      ($lunzip -k -c $inFile | tar xf -) || doFail $inFile
+      ;;
   .bz2)
     (tar jxf $inFile) || doFail $inFile
     ;;
@@ -120,7 +130,7 @@ function buildlib {
   fi
   
 
-  CFLAGS="-arch $ARCH  -m$ABI $moreCFlags" \
+  CFLAGS="-arch $ARCH -m$ABI -ULOCALEDIR -DLOCALEDIR=\\\"${TARGET_DIR}/share/locale\\\" $moreCFlags" \
     CXXFLAGS="-arch $ARCH" \
     ABI=$ABI \
     LDFLAGS="-L$DIST_DIR/lib -arch $ARCH" \
@@ -139,7 +149,7 @@ function buildlib {
 
 # check if pkg-config is installed
 if [ -z $(type -p pkg-config) ]; then
-  echo "ERROR: pkg-config is not installed. This script requires pg-config to be available."
+  echo "ERROR: pkg-config is not installed. This script requires pkg-config to be available."
   echo "Please fix your setup and try again."
   doFail 0
 fi
@@ -160,7 +170,11 @@ if [ $step -le 1 ]; then
     if [ ! -z "$libF" -a -f "$libF" ]; then
       # SHA-1 checksum check
       shsum1=$(echo $l | cut -d '|' -f 2)
-      shsum2=$(shasum $libF | cut -d ' ' -f 1)
+	  algo=1
+	  if [[ ${#shsum1} -eq 64 ]]; then
+		  algo=256
+	  fi
+      shsum2=$(shasum -a $algo $libF | cut -d ' ' -f 1)
       if [ ! -z "$shsum1" -a "$shsum1" != "$shsum2" ]; then
         echo "SHA-1 sums of file $libF don't match"
         echo "expected: $shsum1"
@@ -260,6 +274,14 @@ for l in $(cat $BASEDIR/$LIBS_FILE); do
 done
 
 
+# Remove some unnecessary files.
+if [[ $step -le 31 ]]; then
+	rm -r "$DIST_DIR/share/man" "$DIST_DIR/share/locale" || doFail 31
+fi
+
+
+
+
 if [ $step -le 33 ]; then
   cd $MAIN_PREFIX
   tar jxf $SRC_DIR/gnupg-${GPGVERSION}.tar.bz2 || doFail 33
@@ -294,14 +316,14 @@ if [ $step -le 35 ]; then
   # ld does not support rpath on Mac (see below)
 
   export PATH=$BASE_DIR/bin:$PATH
-  GPGCONFIGPARAM="--enable-tests"
+  GPGCONFIGPARAM=""
 
-  if [ ! -f ./configure ]; then
-    GPGCONFIGPARAM="--disable-tests --enable-maintainer-mode --disable-doc"
+  if [[ ! -f ./configure ]]; then
+    GPGCONFIGPARAM="--enable-maintainer-mode"
     GETTEXT_PREFIX=$DIST_DIR/bin/ ./autogen.sh --force || doFail 35
   fi
 
-  CFLAGS="-arch $ARCH $ADDITIONAL_CFLAGS" \
+  CFLAGS="-arch $ARCH $ADDITIONAL_CFLAGS -ULOCALEDIR -DLOCALEDIR=\\\"${TARGET_DIR}/share/locale\\\"" \
     CXXFLAGS="-arch $ARCH" \
     ABI=$ABI \
     LDFLAGS="-L$DIST_DIR/lib -arch $ARCH" \
@@ -327,54 +349,10 @@ if [ $step -le 35 ]; then
     --with-npth-prefix=$DIST_DIR \
     --with-readline=$DIST_DIR \
     --with-libintl-prefix=$DIST_DIR \
-    --with-adns=$DIST_DIR \
     $GPGCONFIGPARAM \
     --with-libiconv-prefix=$DIST_DIR || doFail 35
 fi
 
-
-
-# tweak Makefiles
-# if [ $step -le 36 ]; then
-#   if [ -d build-aux ]; then
-#     if [ ! -e build-aux/install-sh.orig ]; then
-#       mv build-aux/install-sh build-aux/install-sh.orig || doFail 36
-#     fi
-# 
-# 
-# 	DISTDIR=$(sed 's@/@\\/@g' <<<"$DIST_DIR")
-# 	TARGETDIR=$(sed 's@/@\\/@g' <<<"$TARGET_DIR")
-# 	
-# 
-# 	cat > build-aux/install-sh <<EOT
-# #!/bin/bash
-# param=\$(sed 's@$TARGETDIR@$DISTDIR@g' <<<\$@)
-# \${0%-wrapper}.orig \$param
-# exit \$?
-# EOT
-# 
-# 
-# 
-# 
-#     # dist=$(echo $DIST_DIR | sed 's/\//\\\//g')
-#     # sed 's/##DISTDIR##/'$dist'/' < $BASEDIR/bin/install-sh-wrapper > build-aux/install-sh || doFail 36
-#     chmod +x build-aux/install-sh || doFail 31
-#   fi
-# fi
-
-
-# if [ $step -le 37 ]; then
-# 
-#   dist=$(echo $DIST_DIR | sed 's/\//\\\//g')
-#   sed 's/##DISTDIR##/'$dist'/' < $BASEDIR/bin/install-wrapper > $DIST_DIR/install-wrapper || doFail 37
-#   chmod +x $DIST_DIR/install-wrapper || doFail 37
-# 
-#   for f in $(find . -name Makefile); do
-#     sed 's/\/usr\/bin\/install/'$dist'\/install-wrapper/' < $f > a || doFail 37
-#     sed 's/\/usr\/local\/bin\/ginstall/'$dist'\/install-wrapper/' < $f > a || doFail 37
-#     mv a $f
-#   done
-# fi
 
 if [ $step -le 40 ]; then
   make -j $NCPU || doFail 40
@@ -452,7 +430,11 @@ if [ $step -le 50 ]; then
     bin/kbxutil \
     bin/mpicalc \
     bin/watchgnupg \
-    lib/*dylib libexec share/gnupg share/man | (cd $REL_DIR; tar xf -)
+    lib/*dylib \
+	libexec \
+	share/gnupg \
+	share/man \
+	share/locale | (cd $REL_DIR; tar xf -)
 
 
   cd $REL_DIR/bin
