Automatic detect version.

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -8,8 +8,14 @@ volumeLayout="Installer/DS_Store"
 
 unset REVISION PRERELEASE
 
+temp=$(sed -nE '/.*gnupg-2\.0\.([0-9]+)\.tar.bz2.*/{s//\1/;p;q;}' < "$(dirname "${BASH_SOURCE[0]}")/Formula/MacGPG2.rb")
+if [[ -z "$temp" ]] ;then
+	echo "Unable to find MacGPG2 revision! Possible we are on 2.1?" >&2
+	exit 1
+fi
+
 MAJOR=2
 MINOR=0
-REVISION=22
+REVISION=$temp
 
 source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
